Repository wecode-bootcamp-korea/23-1st-Weeteweete-frontend, pull requests merged in 2021-08, with the labels that each got.

#1 [23기 최호정] Modify : Nav , Footer Layout
  public/index.html
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterLink.js
  src/components/Footer/FooterLink.scss
  src/components/Nav/MenuLink.js
  src/components/Nav/MyPageLink.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/styles/common.scss
  src/styles/reset.scss
  src/styles/variable.scss
Labels: Status: Accepted

#2 [23기 배윤아] Modify : 회원가입 페이지 레이아웃 수정 2
  package-lock.json
  src/Routes.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/SignupData.js
Labels: Status: Accepted

#10 [23기 배윤아] Add : 회원가입 페이지 회원가입 기능 추가
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: Status: Accepted

#4 [23기 배윤아] Add : 아이디 찾기 페이지 레이아웃
  src/pages/Findid/Findid.js
  src/pages/Findid/Findid.scss
  src/pages/Findid/FindidData.js
Labels: Status: Accepted

#12 [23기 배윤아] Add : 로그인 기능 구현
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 리뷰 요청

#6 [23기 이나현] Modify: 컴포넌트 수정 및 기능 추가
  public/data/ItemData.json
  public/data/productDetail.json
  public/images/mockProdectSlide.jpg
  public/images/mockProductDetail.jpg
  public/images/motemoteDetailImg1.jpg
  public/images/motemoteDetailImg2.jpg
  public/images/motemoteDetailImg3.jpg
  public/index.html
  src/Routes.js
  src/pages/Productdetail/ImageSlider.js
  src/pages/Productdetail/ImageSlider.scss
  src/pages/Productdetail/ProductDetailButtons.js
  src/pages/Productdetail/ProductDetailDescription.js
  src/pages/Productdetail/ProductDetailOption.js
  src/pages/Productdetail/Productdetail.js
  src/pages/Productdetail/Productdetail.scss
  src/pages/Productdetail/productDetailInfo.js
Labels: Status: 리뷰 요청

#7 [23기 차예은]Modified: 구매페이지 레이아웃 수정
  package-lock.json
  public/images/btn_prev.gif
  src/Routes.js
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
  src/pages/Payment/PaymentDeliveryInfo.js
  src/pages/Payment/PaymentDeliveryInfo.scss
  src/pages/Payment/PaymentDeliveryInfoData.js
  src/pages/Payment/PaymentDeliveryInfoMockData.json
  src/pages/Payment/PaymentOrderDetails.js
  src/pages/Payment/PaymentOrderDetails.scss
  src/pages/Payment/PaymentTotalPayment.js
  src/pages/Payment/PaymentTotalPayment.scss
Labels: Status: Accepted

#9 [23기 최호정] ADD : list페이지 레이아웃 및 기능구현
  package-lock.json
  package.json
  public/data/ListItemData.json
  public/data/ReviewData.json
  public/images/product_pro1.jpeg
  public/images/review_star.svg
  public/images/review_star_red.svg
  src/Routes.js
  src/pages/Product/ColorChip.js
  src/pages/Product/ColorChip.scss
  src/pages/Product/ProListInList.js
  src/pages/Product/ProListInList.scss
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/pages/Product/Prohead.js
  src/pages/Product/Prohead.scss
  src/pages/Product/Prolist.js
  src/pages/Product/Prolist.scss
  src/pages/Product/Protab.js
  src/pages/Product/Protab.scss
Labels: Status: Conflict 발생

#5 [23기 배윤아] Add : 비밀번호 찾기 페이지 레이아웃 완료
  src/pages/Findid/FindFormLayout.js
  src/pages/Findid/FindFormLayout.scss
  src/pages/Findpw/Findpw.js
  src/pages/Findpw/Findpw.scss
  src/pages/Findpw/FindpwData.js
Labels: Status: 리뷰 요청

#13 [23기 배윤아] Add : 아이디 찾기 기능 추가
  src/pages/Findid/Findid.js
  src/pages/Findid/Findid.scss
  src/pages/Findid/FindidData.js
Labels: Status: 리뷰 요청, Status: Conflict 발생

#14 [23기 배윤아] Add : 비밀번호 찾기 기능 추가
  src/pages/Findpw/Findpw.js
Labels: Status: 리뷰 요청

#11 [23기 배윤아] Add : 회원가입 페이지 유효성 검사 진행중
  src/pages/Findid/Findid.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/SignupData.js
  src/utils/validation.js
Labels: Status: 리뷰 요청

#17 [23기 배윤아] Modify : 구매페이지 주문상품목록 컴포넌트 기능
  public/data/PaymentProductData.json
  src/pages/Payment/PaymentOrderDetails.js
Labels: Status: 리뷰 요청

#18 [23기 차예은]Modified: 구매페이지 수정사항 반영해서 수정
  public/data/paymentTotalPayment.json
  src/config.js
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
  src/pages/Payment/PaymentDeliveryInfo.js
  src/pages/Payment/PaymentDeliveryInfoData.js
  src/pages/Payment/PaymentDeliveryInfoMockData.json
  src/pages/Payment/PaymentOrderDetails.scss
  src/pages/Payment/PaymentTotalPayment.js
  src/pages/Payment/PaymentTotalPayment.scss
  src/pages/Review/ReviewWrite/ReviewWrite.js
Labels: Status: Accepted

#15 [23기 이나현] MODIFY: 수정사항 반영 및 동적 라우팅
  public/data/cartData.json
  src/Routes.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartButton.js
  src/pages/Cart/CartButton.scss
  src/pages/Cart/CartListSection.js
  src/pages/Cart/CartListSection.scss
  src/pages/Cart/CartTotalSection.js
  src/pages/Cart/CartTotalSection.scss
  src/pages/Cart/CartTotalSectionFooter.js
  src/pages/Cart/CartTotalSectionFooter.scss
Labels: Status: 리뷰 요청

#19 [23기 이나현] Modify: 수정사항반영
  src/Routes.js
  src/components/Nav/MyPageLink.js
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/CartListSection.js
  src/pages/Login/Login.js
  src/pages/Product/Prolist.js
  src/pages/Productdetail/Modal.js
  src/pages/Productdetail/Modal.scss
  src/pages/Productdetail/ProductDetailButtons.js
  src/pages/Productdetail/ProductDetailOption.js
  src/pages/Productdetail/Productdetail.js
  src/pages/Review/Review.js
  src/pages/Review/ReviewWrite/ReviewWrite.js
  src/pages/Review/Total.js
Labels: Status: 리뷰 요청

#20 ADD: 최종본1
  public/data/VisualImageData.json
  src/Routes.js
  src/components/Footer/Footer.js
  src/pages/Cart/Cart.js
  src/pages/Cart/CartButton.js
  src/pages/Findid/Findid.js
  src/pages/Findpw/Findpw.js
  src/pages/Main/MainItem.js
  src/pages/Main/MainVisual.scss
  src/pages/Payment/Payment.js
  src/pages/Payment/PaymentDeliveryInfoData.js
  src/pages/Payment/PaymentOrderDetails.js
  src/pages/Payment/PaymentOrderDetails.scss
  src/pages/Payment/PaymentTotalPayment.js
  src/pages/Product/ColorChip.scss
  src/pages/Product/ProListInList.js
  src/pages/Review/ReviewWrite/ReviewWrite.js
  src/pages/Review/Total.js
  src/pages/Signup/Signup.js
Labels: Status: 리뷰 요청
